# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true
[goldmark.parser]
  [goldmark.parser.attribute]
    block = true
    title = true
  wrapStandAloneImageWithParagraph = false
  autoHeadingID = true
  autoHeadingIDType = "github"
[goldmark.extensions]
  linkify = true
[goldmark.extensions.passthrough]
  enable = true
[goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[highlight]
  noClasses = false
  lineNos = true
  lineNumbersInTable = false
  codeFences = true
  guessSyntax = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
