media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/data/blog
    format: yaml-frontmatter
    filename: "{slug}.mdx"
    view:
      primary: title
      fields: [ title, pubDatetime, featured, tags ]
      sort: [ pubDatetime, title ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: pubDatetime
        label: Publish Time
        type: date
        required: true
      - name: modDatetime
        label: Modified Time
        type: date
      - name: featured
        label: Featured
        type: boolean
        default: false
      - name: tags
        label: Tags
        type: string
        list: true
      - name: description
        label: Description
        type: string
      - name: password
        label: Password
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }