name: simple-deploy

on:
  push:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install
    - name: Run jekyll build
      run: bundle exec jekyll build
    - name: Simple deploy with git
      uses: rdarida/simple-github-pages-deploy-action@v1
      with: # optional
        git-user: 'hoochanlon'
        git-email: 'hoochanlon@outlook.com'
        git-base-folder: '_site'
        commit-message: 'deploy'
        branch: 'gh-pages'